# Generated by Django 5.1.4 on 2025-01-13 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_user_password_alter_user_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('Doctor', 'Doctor')], max_length=10),
        ),
    ]
