# Generated by Django 5.1.4 on 2025-01-19 12:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_rename_patient_sugartest_patient_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sugartest',
            name='patient_name',
        ),
        migrations.AddField(
            model_name='sugartest',
            name='patient',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='sugar_tests', to='app.patient'),
            preserve_default=False,
        ),
    ]
